// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenDownloadFolder opens Windows Explorer at target folder safely
 */
export function OpenDownloadFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(2252621405, path);
}

/**
 * SelectDownloadDirectory opens native OS dialog to pick a download directory
 */
export function SelectDownloadDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2425067020);
}

/**
 * SelectTorrentFile opens native OS dialog to pick a .torrent file
 */
export function SelectTorrentFile(): $CancellablePromise<string> {
    return $Call.ByID(709484011);
}

/**
 * ValidateDirectory validates whether a directory path is accessible and writable
 */
export function ValidateDirectory(path: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(4076753050, path);
}
