// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function GetSettings(): $CancellablePromise<models$0.UserSettings> {
    return $Call.ByID(1349737883).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveSettings(settings: models$0.UserSettings): $CancellablePromise<void> {
    return $Call.ByID(2344251778, settings);
}

// Private type creation functions
const $$createType0 = models$0.UserSettings.createFrom;
