// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function AddMagnetLink(magnetURI: string, downloadDir: string): $CancellablePromise<models$0.TorrentItem | null> {
    return $Call.ByID(1056966118, magnetURI, downloadDir).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AddTorrentFile(filePath: string, downloadDir: string): $CancellablePromise<models$0.TorrentItem | null> {
    return $Call.ByID(2730919668, filePath, downloadDir).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetTorrentDetails(id: string): $CancellablePromise<models$0.TorrentDetails | null> {
    return $Call.ByID(2778592835, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetTorrents(): $CancellablePromise<(models$0.TorrentItem | null)[]> {
    return $Call.ByID(1212517824).then(($result: any) => {
        return $$createType4($result);
    });
}

export function PauseTorrent(id: string): $CancellablePromise<void> {
    return $Call.ByID(3536010301, id);
}

export function RemoveTorrent(id: string, deleteFiles: boolean): $CancellablePromise<void> {
    return $Call.ByID(2640746957, id, deleteFiles);
}

export function ResumeTorrent(id: string): $CancellablePromise<void> {
    return $Call.ByID(1783414412, id);
}

export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(8853547);
}

// Private type creation functions
const $$createType0 = models$0.TorrentItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.TorrentDetails.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType1);
