// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * InspectMagnetLink parses a magnet URI and attempts to resolve metadata details (files, total size)
 */
export function InspectMagnetLink(magnetURI: string): $CancellablePromise<models$0.TorrentInspectData | null> {
    return $Call.ByID(4278779964, magnetURI).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * InspectTorrentFile parses a local .torrent file and returns comprehensive metadata details
 */
export function InspectTorrentFile(filePath: string): $CancellablePromise<models$0.TorrentInspectData | null> {
    return $Call.ByID(4202068914, filePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenDownloadFolder opens Windows Explorer at target folder safely
 */
export function OpenDownloadFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(127138150, path);
}

/**
 * SelectDownloadDirectory opens native OS dialog to pick a download directory
 */
export function SelectDownloadDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3744510885);
}

/**
 * SelectTorrentFile opens native OS dialog to pick a .torrent file
 */
export function SelectTorrentFile(): $CancellablePromise<string> {
    return $Call.ByID(3791243422);
}

/**
 * ValidateDirectory validates whether a directory path is accessible and writable
 */
export function ValidateDirectory(path: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3727472099, path);
}

// Private type creation functions
const $$createType0 = models$0.TorrentInspectData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
