// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TorrentDetails {
    "id": string;
    "name": string;
    "hash": string;
    "status": TorrentStatus;

    /**
     * 0.0 to 100.0
     */
    "progress": number;

    /**
     * Bytes per second
     */
    "downloadSpeed": number;

    /**
     * Bytes per second
     */
    "uploadSpeed": number;

    /**
     * Total downloaded
     */
    "downloadedBytes": number;

    /**
     * Total uploaded
     */
    "uploadedBytes": number;

    /**
     * Total size in bytes
     */
    "totalSize": number;

    /**
     * -1 if infinite / unknown
     */
    "etaSeconds": number;
    "seeds": number;
    "peers": number;
    "ratio": number;
    "savePath": string;
    "addedAt": string;
    "completedAt"?: string | null;
    "errorMessage"?: string;
    "files": TorrentFile[];
    "pieceSize": number;
    "pieceCount": number;
    "magnetUri"?: string;

    /** Creates a new TorrentDetails instance. */
    constructor($$source: Partial<TorrentDetails> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = TorrentStatus.$zero;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            this["downloadSpeed"] = 0;
        }
        if (!("uploadSpeed" in $$source)) {
            this["uploadSpeed"] = 0;
        }
        if (!("downloadedBytes" in $$source)) {
            this["downloadedBytes"] = 0;
        }
        if (!("uploadedBytes" in $$source)) {
            this["uploadedBytes"] = 0;
        }
        if (!("totalSize" in $$source)) {
            this["totalSize"] = 0;
        }
        if (!("etaSeconds" in $$source)) {
            this["etaSeconds"] = 0;
        }
        if (!("seeds" in $$source)) {
            this["seeds"] = 0;
        }
        if (!("peers" in $$source)) {
            this["peers"] = 0;
        }
        if (!("ratio" in $$source)) {
            this["ratio"] = 0;
        }
        if (!("savePath" in $$source)) {
            this["savePath"] = "";
        }
        if (!("addedAt" in $$source)) {
            this["addedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("pieceSize" in $$source)) {
            this["pieceSize"] = 0;
        }
        if (!("pieceCount" in $$source)) {
            this["pieceCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TorrentDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): TorrentDetails {
        const $$createField18_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField18_0($$parsedSource["files"]);
        }
        return new TorrentDetails($$parsedSource as Partial<TorrentDetails>);
    }
}

export class TorrentFile {
    "index": number;
    "path": string;
    "size": number;

    /**
     * 0.0 to 100.0
     */
    "progress": number;

    /** Creates a new TorrentFile instance. */
    constructor($$source: Partial<TorrentFile> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TorrentFile instance from a string or object.
     */
    static createFrom($$source: any = {}): TorrentFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TorrentFile($$parsedSource as Partial<TorrentFile>);
    }
}

export class TorrentFileInfo {
    "path": string;
    "size": number;

    /** Creates a new TorrentFileInfo instance. */
    constructor($$source: Partial<TorrentFileInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TorrentFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TorrentFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TorrentFileInfo($$parsedSource as Partial<TorrentFileInfo>);
    }
}

export class TorrentInspectData {
    "name": string;
    "hash": string;
    "totalSize": number;
    "pieceLength": number;
    "numPieces": number;
    "createdBy": string;
    "creationDate": number;
    "sourceFilePath": string;
    "files": TorrentFileInfo[];
    "trackers": string[];

    /** Creates a new TorrentInspectData instance. */
    constructor($$source: Partial<TorrentInspectData> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("totalSize" in $$source)) {
            this["totalSize"] = 0;
        }
        if (!("pieceLength" in $$source)) {
            this["pieceLength"] = 0;
        }
        if (!("numPieces" in $$source)) {
            this["numPieces"] = 0;
        }
        if (!("createdBy" in $$source)) {
            this["createdBy"] = "";
        }
        if (!("creationDate" in $$source)) {
            this["creationDate"] = 0;
        }
        if (!("sourceFilePath" in $$source)) {
            this["sourceFilePath"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("trackers" in $$source)) {
            this["trackers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TorrentInspectData instance from a string or object.
     */
    static createFrom($$source: any = {}): TorrentInspectData {
        const $$createField8_0 = $$createType3;
        const $$createField9_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField8_0($$parsedSource["files"]);
        }
        if ("trackers" in $$parsedSource) {
            $$parsedSource["trackers"] = $$createField9_0($$parsedSource["trackers"]);
        }
        return new TorrentInspectData($$parsedSource as Partial<TorrentInspectData>);
    }
}

export class TorrentItem {
    "id": string;
    "name": string;
    "hash": string;
    "status": TorrentStatus;

    /**
     * 0.0 to 100.0
     */
    "progress": number;

    /**
     * Bytes per second
     */
    "downloadSpeed": number;

    /**
     * Bytes per second
     */
    "uploadSpeed": number;

    /**
     * Total downloaded
     */
    "downloadedBytes": number;

    /**
     * Total uploaded
     */
    "uploadedBytes": number;

    /**
     * Total size in bytes
     */
    "totalSize": number;

    /**
     * -1 if infinite / unknown
     */
    "etaSeconds": number;
    "seeds": number;
    "peers": number;
    "ratio": number;
    "savePath": string;
    "addedAt": string;
    "completedAt"?: string | null;
    "errorMessage"?: string;

    /** Creates a new TorrentItem instance. */
    constructor($$source: Partial<TorrentItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = TorrentStatus.$zero;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("downloadSpeed" in $$source)) {
            this["downloadSpeed"] = 0;
        }
        if (!("uploadSpeed" in $$source)) {
            this["uploadSpeed"] = 0;
        }
        if (!("downloadedBytes" in $$source)) {
            this["downloadedBytes"] = 0;
        }
        if (!("uploadedBytes" in $$source)) {
            this["uploadedBytes"] = 0;
        }
        if (!("totalSize" in $$source)) {
            this["totalSize"] = 0;
        }
        if (!("etaSeconds" in $$source)) {
            this["etaSeconds"] = 0;
        }
        if (!("seeds" in $$source)) {
            this["seeds"] = 0;
        }
        if (!("peers" in $$source)) {
            this["peers"] = 0;
        }
        if (!("ratio" in $$source)) {
            this["ratio"] = 0;
        }
        if (!("savePath" in $$source)) {
            this["savePath"] = "";
        }
        if (!("addedAt" in $$source)) {
            this["addedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TorrentItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TorrentItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TorrentItem($$parsedSource as Partial<TorrentItem>);
    }
}

export enum TorrentStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "Queued",
    StatusChecking = "Checking",
    StatusFetchingMeta = "Fetching Metadata",
    StatusDownloading = "Downloading",
    StatusPaused = "Paused",
    StatusCompleted = "Completed",
    StatusError = "Error",
};

export class UserSettings {
    "downloadDir": string;

    /**
     * Bytes per sec, 0 = unlimited
     */
    "downloadSpeedLimit": number;

    /**
     * Bytes per sec, 0 = unlimited
     */
    "uploadSpeedLimit": number;

    /**
     * "system", "dark", "light"
     */
    "theme": string;
    "maxActiveDownloads": number;

    /**
     * Zoom scale percentage (e.g., 100, 110, 90)
     */
    "uiScale": number;

    /** Creates a new UserSettings instance. */
    constructor($$source: Partial<UserSettings> = {}) {
        if (!("downloadDir" in $$source)) {
            this["downloadDir"] = "";
        }
        if (!("downloadSpeedLimit" in $$source)) {
            this["downloadSpeedLimit"] = 0;
        }
        if (!("uploadSpeedLimit" in $$source)) {
            this["uploadSpeedLimit"] = 0;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("maxActiveDownloads" in $$source)) {
            this["maxActiveDownloads"] = 0;
        }
        if (!("uiScale" in $$source)) {
            this["uiScale"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): UserSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserSettings($$parsedSource as Partial<UserSettings>);
    }
}

// Private type creation functions
const $$createType0 = TorrentFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TorrentFileInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
